[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Removed the Next.js plugin which might be causing issues

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
